//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cus
    {
        public int ID { get; set; }
        public string Cus_Name { get; set; }
        public string Cus_Email { get; set; }
        public string Cus_Phone { get; set; }
        public byte[] Cus_Image { get; set; }
    }
}
