//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pur
    {
        public int ID { get; set; }
        public Nullable<int> Cat_ID { get; set; }
        public Nullable<int> Supp_ID { get; set; }
        public string Pur_Name { get; set; }
        public string Pur_Type { get; set; }
        public string Pur_Cat { get; set; }
        public string Pur_Supp { get; set; }
        public string Pur_Det { get; set; }
        public Nullable<double> Pur_Buy { get; set; }
        public Nullable<double> Pur_Sell { get; set; }
        public Nullable<double> Pur_Qu { get; set; }
        public Nullable<double> Pur_TBuy { get; set; }
        public Nullable<double> Pur_TSell { get; set; }
        public Nullable<double> Pur_TProf { get; set; }
    
        public virtual TB_Cat TB_Cat { get; set; }
        public virtual TB_Supp TB_Supp { get; set; }
    }
}
