//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Sal
    {
        public int ID { get; set; }
        public string Sal_Name { get; set; }
        public string Sal_Cus { get; set; }
        public Nullable<double> Sal_Sell { get; set; }
        public Nullable<double> Sal_Qt { get; set; }
        public Nullable<double> Sal_TSell { get; set; }
        public Nullable<System.DateTime> Sal_Date { get; set; }
    }
}
