//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_User
    {
        public int ID { get; set; }
        public string User_Name { get; set; }
        public string User_Pass { get; set; }
        public string User_Roll { get; set; }
        public string User_Status { get; set; }
    }
}
